name: Create artifacts from MITE data

run-name: Pushed by ${{ github.actor }}

permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths:
      - "mite_data/data/**"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Get changed MITE files
        id: files
        run: |
          CHANGED=$(git diff --name-only --diff-filter=AM ${{ github.event.before }}...${{ github.sha }})
          echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"

      - name: Debug output
        run: |
          echo "OUTPUT:"
          echo "${{ steps.files.outputs.changed }}"
          echo "END"

      - name: Run artifact creation pipeline
        if: steps.files.outputs.changed
        run: |
          echo "Running artifact creation on MITE .json files:"
          while IFS= read -r file; do
            echo "  -> $file"
            uv run python pipeline/create_artifacts.py "$file"
          done <<< "${{ steps.files.outputs.changed }}"

      - name: Commit changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          git status 
          
          if ! git diff --cached --quiet; then
            git commit -m "Update generated artifacts"
            git push
          fi